from .view_doctor import *
from .view_patient import *
from .view_visit import *
from .view_comment import *
from .view_user import *
from .view_auth import *
from .view_diagnosis import *
from .view_laboratory_test import *
from .view_prescription import *
from .view_allergy import *
from .view_dashboard import *
